Fail after 3 install tries

diff --git a/basebox/scripts/firstboot.d/20updates b/basebox/scripts/firstboot.d/20updates
--- a/basebox/scripts/firstboot.d/20updates
+++ b/basebox/scripts/firstboot.d/20updates
@@ -31,12 +31,16 @@ rmdir /etc/udev/rules.d/70-persistent-net.rules && echo "Removed empty /etc/udev
     apt-get update
 
     # Upgrade whatever we can
-    for i in 1 2 3
+    for i in 3 2 1
     do
         if apt-get -y -o Dpkg::Options::="--force-confnew" dist-upgrade; then
             break
         else
-            notice "apt-get dist-upgrade failed RET=$? RETRY=$i"
+            if [ "$i" -gt 1 ]; then
+                notice "apt-get dist-upgrade failed RET=$? RETRY=$i"
+            else
+                error "apt-get dist-upgrade failed RET=$?" 129
+            fi
         fi
     done
 
@@ -44,12 +48,16 @@ rmdir /etc/udev/rules.d/70-persistent-net.rules && echo "Removed empty /etc/udev
 
     echo ">> PACKAGES: $PACKAGES $EXTRAS"
 
-    for i in 1 2 3
+    for i in 3 2 1
     do
         if apt-get -y install $PACKAGES $EXTRAS; then
             break
         else
-            notice "apt-get failed RET=$? RETRY=$i"
+            if [ "$i" -gt 1 ]; then
+                notice "apt-get install failed RET=$? RETRY=$i"
+            else
+                error "apt-get install failed RET=$?" 130
+            fi
         fi
     done
 
