Add OPENRESTY_PORT config, change to 44480 by default

diff --git a/basebox/scripts/firstboot.d/50openresty b/basebox/scripts/firstboot.d/50openresty
--- a/basebox/scripts/firstboot.d/50openresty
+++ b/basebox/scripts/firstboot.d/50openresty
@@ -6,11 +6,12 @@
 #
 # Created: Fri Jan  1 05:41:23 EST 2016
 #
-# Depends: OPENRESTY_REPO
+# Depends: OPENRESTY_REPO OPENRESTY_PORT
 # Optional: OPENRESTY_VERSION
 
 # Required
 [ -n "$OPENRESTY_REPO" ] || error "Missing OPENRESTY_REPO, please fix." 150
+[ -n "$OPENRESTY_PORT" ] || error "Missing OPENRESTY_PORT, please fix." 150
 
 if [ -z "$OPENRESTY_VERSION" ]; then
     echo "OPENRESTY_VERSION not set, assuming 'latest'"
@@ -72,11 +73,11 @@ mkdir "${OPENRESTY_DIR}/nginx/lua" && echo "Created ${OPENRESTY_DIR}/nginx/lua"
 # make clean
 # cd ..;rm -fr $OPENRESTY_TAR $dir
 
-# Configure to listen on 8080 fasttrack/scripts/rc.fasttrack.d/10openresty will forward 80 to 8080
-# We do this so the server runs as the swgemu server id doesn't have to run as root
-sed 's/listen \([ ]*\)80;/listen\1 8080;/' -i ${OPENRESTY_DIR}/nginx/conf/nginx.conf
+# Configure to listen on OPENRESTY_PORT fasttrack/scripts/rc.fasttrack.d/10openresty will forward 80 to OPENRESTY_PORT
+# We do this so the server runs as the swgemu server uid and doesn't have to run as root
+perl -pe 's/listen(\s+)\d+/listen${1}'${OPENRESTY_PORT}'/ if(m!^\s+listen\s+\d+;!)' -i ${OPENRESTY_DIR}/nginx/conf/nginx.conf
 
-# Add /zonama-instance-id service
+# Add /zonama-instance-id service to support auto-discovery
 perl -pe 'print("        location /zonama-instance-id { alias /var/lib/dbus/machine-id; }\n\n") if(m!^\s+location /\s+{!)' -i ${OPENRESTY_DIR}/nginx/conf/nginx.conf
 
 # Number of workers, cpus/2 or at least 2
diff --git a/fasttrack/scripts/devsetup.d/01-iplist b/fasttrack/scripts/devsetup.d/01-iplist
--- a/fasttrack/scripts/devsetup.d/01-iplist
+++ b/fasttrack/scripts/devsetup.d/01-iplist
@@ -6,12 +6,13 @@
 #
 # Created: Sat Jan 16 10:37:28 EST 2016
 #
-# Depends: IPLIST
+# Depends: IPLIST OPENRESTY_PORT
 #
 # NOTE: We run this in the background to give it a head start before the devsetup needs the list
 #
 
-[ -n "$IPLIST" ] || error "Missing IPLIST configuration"
+[ -n "$IPLIST" ] || error "Missing IPLIST configuration" 101
+[ -n "$OPENRESTY_PORT" ] || error "Missing OPENRESTY_PORT configuration" 101
 
 update_iplist() {
   (
@@ -53,10 +54,10 @@ update_iplist() {
     # A unique id so we can see these across multiple logs etc.
     local scan_token=$(date|md5sum|cut -d' ' -f1)
 
-    read -a instance_query <<<$(curl -s -D - -A zonamaipscan --connect-timeout 5 -m 5 'http://127.0.0.1:8080/zonama-instance-id?scantoken='$scan_token 2> /dev/null)
+    read -a instance_query <<<$(curl -s -D - -A zonamaipscan --connect-timeout 5 -m 5 'http://127.0.0.1:'${OPENRESTY_PORT}'/zonama-instance-id?scantoken='$scan_token 2> /dev/null)
 
     if [ "${instance_query[1]}" != "200" ]; then
-	echo "Local zonama-instance-id service is not running on port 8080 as expected, giving up."
+	echo "Local zonama-instance-id service is not running on port ${OPENRESTY_PORT} as expected, giving up."
 	return 1
     fi
 
@@ -73,7 +74,7 @@ update_iplist() {
     do
 	# echo -ne "\r$i\t"
 	local addr="${subnet}${i}"
-	local result=$(curl -s -A zonamaipscan --connect-timeout 0.02 -m 0.02 'http://'${addr}':8080/zonama-instance-id?scantoken='$scan_token 2>/dev/null)
+	local result=$(curl -s -A zonamaipscan --connect-timeout 0.02 -m 0.02 'http://'${addr}':'${OPENRESTY_PORT}'/zonama-instance-id?scantoken='$scan_token 2>/dev/null)
 
 	if [ "X$result" = "X$our_instance" ]; then
 	    # TODO do we need to double check nginx log local just in case?
