Add postdebug to post gist/issue with diagnostics.
Add postdebug command to ~/bin/swgemu.

It can ask user if they would like to open an issue or if they want to
post a gist.  They will be prompted to login if they want an issue and
optionally they can post a gist w/o logging in to post an annonymous
gist for sharing.

Provides the URL after it runs so the user can share in IRC or via some
other mechanism to get help.

diff --git a/fasttrack/bin/swgemu b/fasttrack/bin/swgemu
--- a/fasttrack/bin/swgemu
+++ b/fasttrack/bin/swgemu
@@ -39,13 +39,14 @@ main() {
     case $cmd in
 	'backup' ) server_backup ;;
 	'build' ) server_build ;;
-	'latest' ) server_latest $@ ;;
-	'send' ) server_send $@ ;;
+	'latest' ) server_latest "$@" ;;
+	'postdebug' ) post_debug "$@";;
+	'send' ) server_send "$@" ;;
 	'start' ) server_start ;;
 	'status' ) server_status ;;
 	'stop' ) server_stop;;
 	'version' ) show_version;;
-	* ) echo "Usage: $0 {backup|build|latest|send|start|status|stop|version}"; exit 1 ;;
+	* ) echo "Usage: $0 {backup|build|postdebug|latest|send|start|status|stop|version}"; exit 1 ;;
     esac
 
     ret=$?
@@ -396,10 +397,21 @@ show_version()
     local me=$(pwd -P)'/'$(basename ${BASH_SOURCE[0]})
     popd > /dev/null
     local tmp=$(mktemp /tmp/swgemu-version-temp.XXXXXX)
+
+    # Hack to avoid prompting user for pw's so they just fail instantly if not setup
+    # Nothing nicer until git 2.3 :-(
+    local tmpssh=$(mktemp ~/.swgemu-ssh-temp.XXXXXX.tmp)
+    echo 'ssh -oBatchMode=yes "$@"' > $tmpssh
+    chmod 700 "${tmpssh}"
+    export GIT_SSH="${tmpssh}"
+
     local git_remote=$(cd ${BUILD_DIR};git ls-remote origin refs/heads/unstable 2>> ${tmp} | cut -f1)
     local git_local=$(cd ${BUILD_DIR};git rev-parse refs/heads/unstable 2>> ${tmp})
     local zd_tag=$(cd ~/ZonamaDev;git describe --tag 2>> ${tmp})
     local me_md5=$(md5sum < $me|cut -d' ' -f1 2>&1)
+
+    unset GIT_SSH
+    rm -f "${tmpssh}"
 
     read name url junk <<< $(cd ${BUILD_DIR};git remote -v 2>>${tmp})
 
@@ -415,6 +427,111 @@ show_version()
     json="$json }"
 
     echo $json | python -m json.tool
+}
+
+post_debug()
+{
+    local title="$1"
+    local desc="$2"
+    local gori="$3"
+
+    if [ -z "$title" ]; then
+	read -p "Title: " title
+	echo
+    fi
+
+    if [ -z "$desc" ]; then
+	read -p "One-line description of your problem: " desc
+	echo
+    fi
+
+    if [ -z "$gori" ]; then
+	read -p 'Post a [G]ist or an [I]ssue? ' gori
+    fi
+
+    local url=""
+
+    case $gori in
+	[Ii]* )
+	    type ghi > /dev/null 2>&1 || (set -x;sudo gem install ghi)
+
+	    if git config --get ghi.token; then
+		:
+	    else
+		echo "Please login to github to post an issue:"
+		read -p "What is your github username? " ghuser
+
+		if [ -z "$ghuser" ]; then
+		    echo "** Can't post an issues without a github account, please try again with a gist or provide your github username."
+		    echo "** ABORTED BY USER **"
+		    return 2
+		fi
+
+		ghi config --auth $ghuser
+	    fi
+	    echo "** Posting Issue..."
+	    local issue=$(ghi open --label "type/automated-help" -m "$(post_debug_body)" -- lordkator/ZonamaDev 2>&1)
+	    echo "** Looking for issue id"
+	    local issue_num=$(echo "$issue"|sed -ne '1s!^#\([0-9][0-9]*\):.*!\1!p')
+
+	    if [ -n "$issue_num" ]; then
+		echo "** Found issue #${issue_num}"
+		url="https://github.com/lordkator/ZonamaDev/issues/"${issue_num}
+	    else
+		echo -e "WARNING: Unexpected output from ghi:\n\t${issue}\n\nGET HELP!"
+	    fi
+	    ;;
+	* | [Gg]* )
+	    type gist > /dev/null 2>&1 || (set -x;sudo gem install gist)
+
+	    if [ ! -f ~/.gist ] && yorn "Would you like to use your github userid for this? "; then
+		gist --login
+	    fi
+
+	    url=$(post_debug_body | gist -p -d "swgemu postdebug - ${title}" -f "ZonamaDev/post_debug-"$(date +%s)".md" 2>&1)
+	    ;;
+    esac
+
+    if [ -z "$url" ]; then
+	echo "** WARNING: Something seems to have failed, look for clues in any errors above."
+	return 1
+    fi
+
+    echo -e "\nShare this URL to get help: ${url}"
+    return 0
+}
+
+post_debug_body() {
+    # The output here will be included in the post as github flavored markdown content
+    # Note: Can't be too long as it goes into the command line with ghi and thus is limited
+    #       see: xargs --show-limits < /dev/null
+    #
+    exec 2>&1
+    echo -e "swgemu postdebug - ${title}\n\n"
+    date
+    echo -e "\nDescription: ${desc}\n\n"
+
+    # Check various status files
+    echo -e '\nStatus Files:\n```\n'
+    for i in ~/.*.ran
+    do
+       echo "$i: "$(<$i)
+    done
+
+    # Commands to run and capture ouput
+    for cmd in \
+        'show_version' \
+	'tail -5 ~/workspace/Initial_Core3_Build.log' \
+        'tail -100 ~/workspace/Core3/MMOCoreORB/bin/log/core3.log' \
+        'uname -a' \
+	'df -h' \
+	'top -Hbn 1' \
+
+    do
+	echo -e '\n```\n---\n'"${cmd}"'\n```\n'
+	$cmd
+    done
+    echo -e '\n```'
 }
 
 server_latest()
@@ -529,6 +646,6 @@ get_lock() {
     trap 'release_lock;' 0
 }
 
-main $@
+main "$@"
 
 exit 0
