Add build option and usage

diff --git a/fasttrack/bin/swgemu b/fasttrack/bin/swgemu
--- a/fasttrack/bin/swgemu
+++ b/fasttrack/bin/swgemu
@@ -46,6 +46,9 @@ server_start() {
 	    else
 		exit $?
 	    fi
+	else
+	    echo "** USER ABORTED **"
+	    exit 2
 	fi
     fi
 
