Fix ip detection

diff --git a/fasttrack/scripts/devsetup.d/01-iplist b/fasttrack/scripts/devsetup.d/01-iplist
--- a/fasttrack/scripts/devsetup.d/01-iplist
+++ b/fasttrack/scripts/devsetup.d/01-iplist
@@ -158,17 +158,18 @@ get_instance() {
     local scan_token=$1
 
     read -a instance_query -d '\0' <<<$(curl -s -D - -A zonamaipscan --connect-timeout 5 -m 5 'http://127.0.0.1:'${OPENRESTY_PORT}'/zonama-instance-id?scantoken='$scan_token 2> /dev/null)
+
     for i in 15 14 13 12 11 10 9 8 7 6 5 4 3 2 1
     do
-	read -a instance_query -d '\0' <<<$(curl -s -D - -A zonamaipscan --connect-timeout 5 -m 5 'http://127.0.0.1:'${OPENRESTY_PORT}'/zonama-instance-id?scantoken='$scan_token 2> /dev/null)
-
 	if [ "${instance_query[1]}" = "200" ]; then
-	    echo "** Found zonama-instance-id service on localhost." >&2
+            echo "** Found zonama-instance-id (${instance_query[${#instance_query[@]}-1]}) on localhost." >&2
 	    break
 	fi
 
 	echo "** Waiting $i seconds for nginx zonama-instance-id service to start" >&2
 	sleep 1
+
+	read -a instance_query -d '\0' <<<$(curl -s -D - -A zonamaipscan --connect-timeout 5 -m 5 'http://127.0.0.1:'${OPENRESTY_PORT}'/zonama-instance-id?scantoken='$scan_token 2> /dev/null)
     done
 
     if [ "${instance_query[1]}" != "200" ]; then
@@ -211,7 +212,7 @@ check_ip() {
 
     # Try SSL first
     local scheme='https'
-    local result=$(curl -s -A zonamaipscan --insecure --connect-timeout 5 -m 5 ${scheme}'://'${server_ip}':'${OPENRESTY_SSL_PORT}'/zonama-instance-id?scantoken='$scan_token 2>/dev/null)
+    local result=$(curl -sk -A zonamaipscan --insecure --connect-timeout 5 -m 5 ${scheme}'://'${server_ip}':'${OPENRESTY_SSL_PORT}'/zonama-instance-id?scantoken='$scan_token 2>/dev/null)
 
     # If that fails fall back to HTTP
     if [ -z "$result" ]; then
@@ -223,6 +224,8 @@ check_ip() {
     if [ "X$result" = "X$our_instance" ]; then
 	echo "** Found ourselves at server_ip (${scheme}://${server_ip}/)"
         return 0
+    else
+        echo "** ERROR: Instance id mis-match, got ($result) expected ($our_instance)"
     fi
 
     alert "Invalid Server IP" "Server IP was ${server_ip}, but it does not appear to be valid anymore.\nRe-running IP setup."
