Add messages and status check to clone

diff --git a/fasttrack/scripts/devsetup.d/25clone b/fasttrack/scripts/devsetup.d/25clone
--- a/fasttrack/scripts/devsetup.d/25clone
+++ b/fasttrack/scripts/devsetup.d/25clone
@@ -24,13 +24,19 @@ check_repos() {
 	return
     fi
 
-    if zenity --question  --text="You're missing the following repos: $missing\n\nWould you like to clone them now?"; then
+    if zenity --question  --text="You're missing the following repos:\n\n\t\t$missing\n\nWould you like to clone them now?"; then
 	local status_pipe=$(mktemp /tmp/clone-status-pipe-XXXXXX)
+	local status_file=$(mktemp /tmp/clone-status-file-XXXXXX)
 
+	echo 255 > $status_file
 	mknod $status_pipe p
 	command_window "Clone Status" "tail -f $status_pipe"  &
 
-	(set -x
+	(
+	echo 254 > $status_file
+	echo -e 'H4sIACYziVYAA5WSYQpAIQiD/3eKwe5/x8h8ZaweKlE2PmyMyFEA6Y0Xff90P9vSA2UdRf+BrU/D\nc2VhU9PwMH7CyUAMFvp+f8UXpqrFKhxfBraT12QCBRuswPJvNJAZXwcxETL5fgIAAA=='|base64 -d|gunzip
+	trap 'echo $? > '${status_file}';echo -e "H4sIAC81iVYAA1NWBgMFIAATQArMg3IUlKHyEIoLJgxSAFOvgKwchUZSjzATv3plZOuVMdWjynOh\nO5NY9+A0n6B6qP0owQIPHi4ArjNqZE8BAAA="|base64 -d|gunzip' 0
+	set -xe
 	for i in $missing
 	do
 	    git clone --progress ssh://${GERRIT_HOST}/${i}.git
@@ -43,11 +49,20 @@ check_repos() {
 		(set -x;cd $i;git checkout -b unstable origin/unstable; sed -e '/push = /d' -e '/url/s!$!\n\tpush = HEAD:refs/for/unstable!' -i .git/config)
 	    fi
 	done
-	echo "** DONE **"
+	set +xe
+	echo -e 'H4sIAJ00iVYAA1NQBgEFBSBSAJNQPoxWVkZmwMS5YMrx0wro4lzYxRVw01wKaA7EUAF1F5oDFVCU\n47YI3TpyPYYebkSGIxcAebZM9YABAAA='|base64 -d|gunzip
+	trap - 0
+	echo 0 > $status_file
 	) 2>&1 | tee $status_pipe
-	zenity --info --text="Clone process complete\nPress [OK] to discard the log window"
+	local ret=(cat $status_file 2> /dev/null)
+
+	if [ -z "$ret" -o $ret -gt 0 ]; then
+	    error "Clone failed with error code $ret\n\nReview the log output for clues." 125
+	else
+	    zenity --info --text="Clone process success.\n\nPress [OK] to discard the log window"
+	fi
 	fuser -k $status_pipe
-	rm -f $status_pipe
+	rm -f $status_pipe $status_file
     else
 	notice "Git Repositories Missing" "Need to clone: $missing\nYou will not be able to build the server until you complete this step."
 	exit 203
