Handle missing sql files as warning rather than fatal. (#46)

diff --git a/fasttrack/scripts/devsetup.d/30mysql-init b/fasttrack/scripts/devsetup.d/30mysql-init
--- a/fasttrack/scripts/devsetup.d/30mysql-init
+++ b/fasttrack/scripts/devsetup.d/30mysql-init
@@ -42,8 +42,12 @@ mysql_init_database() {
 
     for i in ~/workspace/Core3/MMOCoreORB/sql/swgemu.sql ~/workspace/Core3/MMOCoreORB/sql/updates/deletedcharacters_add_dbdeleted.sql ~/workspace/Core3/MMOCoreORB/sql/updates/account_ips.sql
     do
-	echo "Run $i against database"
-	mysql < $i || error "mysql failed while reading $i" 130
+        if [ -f $i ]; then
+            echo "Run $i against database"
+            mysql < $i || error "mysql failed while reading $i" 130
+        else
+            echo "WARNING: $i missing, might be newer code base, after October 18, 2018 these were merged into swgemu.sql"
+        fi
     done
 
     mysql -ve "GRANT ALL PRIVILEGES ON ${DBName}.* TO '${DBUser}'@'localhost';" || error "Failed to grant access on ${DBName} to ${DBUser} user!?" 130
